blogs/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from blogs.views import BlogListView,BlogDetailView, BlogCommentView
app_name = 'blogs'





urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('comment/<int:pk>/', BlogCommentView.as_view(), name='comment'),

]

conf/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = i18n_patterns(
            path('admin/', admin.site.urls),
            path('', include('pages.urls', namespace="pages")),
            path('blogs/', include('blogs.urls', namespace="blogs")),
            path('products/', include('products.urls', namespace="products")),
            path('users/', include('users.urls', namespace="users")),
            path('orders/', include('orders.urls', namespace="orders"))

)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path

from orders.views import CheckoutView, order_create, order_history_view

app_name = 'orders'

urlpatterns = [
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order/', order_create, name='order'),
    path('history/', order_history_view, name='history'),
]

pages/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from pages.views import HomePageView, ContactTemplateView, ThankYouView, FaqListView

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('contact/', ContactTemplateView.as_view(), name='contact'),
    path('contact/thank_you/', ThankYouView.as_view(), name='thank_you'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('faq/', FaqListView.as_view(), name='faq'),

]

products/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from products.views import ProductListView, ProductDetailView, add_or_remove, add_or_remov

app_name = 'products'





urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('detail/<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('cart/<int:pk>/', add_or_remove, name='add_or_remove'),
    path('wish/<int:pk>/', add_or_remov, name='add_or_remov')

]

users/urls.py
from django.urls import path
from users.views import LoginView, RegisterView, verify_email, logout_view, About, AccountView, CartView, WishlistView

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify/email',verify_email, name='code'),
    path('logout/', logout_view ,name='logout'),
    path('about/', About.as_view(), name='about'),
    path('accounts/', AccountView.as_view(), name='accounts'),
    path('cart/', CartView.as_view(), name='cart'),
    path('wishlist/', WishlistView.as_view(), name='wishlist'),

]

users/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _
UserModel = get_user_model()


class VerificationCodeModel(models.Model):
    objects = None
    code = models.CharField(max_length=6, unique=True)
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name='verification_codes')
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = _('Verification Code')
        verbose_name_plural = _('Verification Codes')


class TeamModel(models.Model):
    objects = None
    name = models.CharField(max_length=50)
    profession = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = _('name')
        verbose_name_plural = _('names')

class AccountModel(models.Model):
    user = models.OneToOneField(UserModel, on_delete=models.CASCADE, related_name='accounts')
    full_name = models.CharField(max_length=100, null=True, blank=True)
    company = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    phone = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return str(self.full_name)

    class Meta:
        verbose_name = _('Account')
        verbose_name_plural = _('Accounts')

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from users.models import AccountModel

UserModel = get_user_model()

class RegisterForm(UserCreationForm):
    class Meta:
        model = UserModel
        fields = ('username', 'email', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if UserModel.objects.filter(email=email).exists():
            raise forms.ValidationError('Email already exists')
        return email

class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=254, required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)

class EmailVerificationForm(forms.Form):
    code = forms.CharField(max_length=6)

class AccountModelForm(forms.ModelForm):
    class Meta:
        model = AccountModel
        exclude = ['user']

users/views.py
from decimal import Decimal

from django.contrib import messages
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django.db.models import Sum
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, CreateView, FormView, UpdateView, ListView
import random
from conf import settings
from products.models import ProductModel
from users.models import VerificationCodeModel, TeamModel, AccountModel

from users.forms import RegisterForm, EmailVerificationForm, LoginForm, AccountModelForm


UserModel = get_user_model()


def send_email_verification(user):
    random_code = random.randint(100000, 999999)

    if VerificationCodeModel.objects.filter(code=random_code).exists():
        send_email_verification(user)
    else:
        VerificationCodeModel.objects.create(
            code=random_code,
            user=user
        )
        try:
            send_mail(
                'Verification code',
                f'Verification code for {random_code}',
                settings.EMAIL_HOST_USER,
                [user.email]
            )
            return True
        except Exception as e:
            print(e)
            return False


class RegisterView(CreateView):
    template_name = 'users/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('users:code')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        # send verification code
        send_email_verification(user)
        return super().form_valid(form)

    def form_invalid(self, form):
        storage = messages.get_messages(self.request)
        storage.used = True
        messages.error(self.request, form.errors)
        return self.render_to_response(self.get_context_data(form=form))


def verify_email(request):
    storage = messages.get_messages(request)
    storage.used = True
    if request.method == 'POST':
        form = EmailVerificationForm(request.POST)
        if form.is_valid():
            code = form.cleaned_data['code']
            user_code = VerificationCodeModel.objects.filter(code=code).first()
            if user_code:
                UserModel.objects.filter(pk=user_code.user.pk).update(is_active=True)
                messages.success(request, 'Email verified successfully.')
                return redirect(reverse_lazy('users:login'))
            else:
                messages.error(request, 'This code is invalid')
        else:
            messages.error(request, 'Form submission error')
    else:
        form = EmailVerificationForm()

    return render(request, 'users/code.html', {'form': form})


class LoginView(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('pages:home')

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            login(self.request, user)
            messages.success(self.request, 'Successfully logged in')
            print(f'Authenticated user: {user}')
            print(f'Success URL: {self.success_url}')
            return redirect(self.success_url)
        else:
            messages.error(self.request, 'Invalid username or password')
            return self.render_to_response(self.get_context_data(form=form))

    def form_invalid(self, form):
        for field, errors in form.errors.items():
            for error in errors:
                messages.error(self.request, f"Error in {field}: {error}")
        return self.render_to_response(self.get_context_data(form=form))

def logout_view(request):
    if request.method == 'GET':
        logout(request)
        return redirect(reverse_lazy('pages:home'))



class About(TemplateView):
    template_name = 'users/about-us.html'
    model = TeamModel
    context_object_name = 'teams'

    def get_context_data(self, **kwargs):
        content = super().get_context_data(**kwargs)
        content['teams'] = TeamModel.objects.all()

        return content

class AccountView(LoginRequiredMixin, UpdateView):
    template_name = 'users/accounts.html'
    form_class = AccountModelForm
    success_url = reverse_lazy('pages:home')
    context_object_name = 'account'
    login_url = reverse_lazy('users:login')

    def get_object(self, queryset=None):
        account = AccountModel.objects.get(user=self.request.user)
        return account


class CartView(ListView):
    template_name = 'users/cart.html'
    context_object_name = 'products'
    model = ProductModel

    def get_queryset(self):
        cart = self.request.session.get('cart', [])
        products = ProductModel.objects.filter(pk__in=cart)
        return products

    def calculate_total_price(self):
        cart = self.request.session.get('cart', [])
        products = ProductModel.objects.filter(pk__in=cart)
        total_price = Decimal('0.00')
        for product in products:
            product_price = product.get_price()
            if product_price is not None:
                total_price += product_price
        return total_price

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_price'] = self.calculate_total_price()
        return context


class WishlistView(ListView):
    template_name = 'users/wishlist.html'
    context_object_name = 'products'
    model = ProductModel

    def get_queryset(self):
        wish = self.request.session.get('wish', [])
        products = ProductModel.objects.filter(pk__in=wish)
        return products

    def calculate_total_price(self):
        wish = self.request.session.get('wish', [])
        products = ProductModel.objects.filter(pk__in=wish)
        total_price = Decimal('0.00')
        for product in products:
            product_price = product.get_price()
            if product_price is not None:
                total_price += product_price
        return total_price

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_price'] = self.calculate_total_price()
        return context

templates/users/accounts.html
{% load static %}
{% load i18n %}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <style>
           *,
                *:before,
                *:after {
                    box-sizing: border-box;
                    margin: 0;
                    padding: 0;
                }

                body {
                    font-family: 'Open Sans', Helvetica, Arial, sans-serif;
                     background:url('https://wallbox.ru/resize/2560x1600/wallpapers/main2/201732/1502561450598f44aaccc176.46698383.jpg');
                     height: 100px;

                     background-size: cover;

                    }

                .register-form {
                    background-color: #f9f9f9;
                    padding: 20px;
                    border-radius: 10px;
                     margin: 20px auto;  /* tepa va pastda 20px bo'sh joy qoldirish */
                    max-width: 500px;   /* maksimal kenglik */
                    width: 100%;
                }

                .title-page {
                    margin-bottom: 10px;
                }

    </style>
</head>
<!-- shop-list-left-sidebar31:48-->
{% include 'layouts/head.html' %}
    <body>
    <!--[if lt IE 8]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
        <!-- Begin Body Wrapper -->
        <div class="body-wrapper">
            <!-- Begin Header Area -->
            {% include 'layouts/header-base.html' %}
            <!-- Header Area End Here -->
            <!-- Begin Li's Breadcrumb Area -->
            <div class="breadcrumb-area">
                <div class="container">
                    <div class="breadcrumb-content">
                        <ul>
                            <li><a href="{% url 'pages:home' %}">{% trans 'Home' %}</a></li>
                            <li class="active">{% trans 'Account' %} </li>
                        </ul>
                    </div>
                </div>
            </div>

<div id="wrapper-site">
            <div class="container">
                <div class="row">
                    <div id="content-wrapper" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 onecol">
                        <div id="main">
                            <div id="content" class="page-content">
                                <div class="register-form text-center">
                                    <h3 class="text-center title-page">{% trans 'Updated Account' %}</h3>
                                    {% if messages %}
                                        {% for error in messages %}
                                            <h6 style="color: red">{{ error }}</h6>
                                        {% endfor %}
                                    {% endif %}
                                    <form action="{% url 'users:accounts' %}" id="customer-form" class="js-customer-form" method="post">
                                        {% csrf_token %}
                                        <div>
                                            <div class="form-group">
                                                <div>
                                                    <input style="text-align: center" value="{{ account.full_name }}" class="form-control" name="full_name" type="text" placeholder="{% trans 'Full name' %}">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div>
                                                    <input style="text-align: center" value="{{ account.city }}" class="form-control" name="city" type="text" placeholder="{% trans ' City' %}">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div>
                                                    <input style="text-align: center" value="{{ account.phone }}" class="form-control" name="phone" type="text" placeholder="{% trans 'Phone' %}">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div>
                                                    <input style="text-align: center" value="{{ account.address }}" class="form-control" name="address" type="text" placeholder="{% trans 'Address' %}">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div>
                                                    <input style="text-align: center" value="{{ account.company }}" class="form-control" name="company" type="text" placeholder="{% trans 'Company' %}">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="clearfix">
                                            <div>
                                                <button class="btn btn-primary" data-link-action="sign-in" type="submit">
                                                   {% trans 'Updated Account' %}
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
 <!-- Content Wraper Area End Here -->
            <!-- Begin Footer Area -->
            {% include 'layouts/footer.html' %}
            <!-- Footer Area End Here -->
            <!-- Begin Quick View | Modal Area -->
            <!-- Quick View | Modal Area End Here -->
        </div>
        <!-- Body Wrapper End Here -->
        <!-- jQuery-V1.12.4 -->
       {% include 'layouts/script.html' %}
    </body>

<!-- shop-list-left-sidebar31:48-->
</html>

templates/users/cart.html
{% load static %}
{% load my_tags %}
{% load i18n %}
<!doctype html>
<html class="no-js" lang="zxx">
    
<!-- shopping-cart31:32-->
{% include 'layouts/head.html' %}
    <body>
    <!--[if lt IE 8]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
        <!-- Begin Body Wrapper -->
        <div class="body-wrapper">
            <!-- Begin Header Area -->
            {% include 'layouts/header-base.html' %}
            <!-- Header Area End Here -->
            <!-- Begin Li's Breadcrumb Area -->
            <div class="breadcrumb-area">
                <div class="container">
                    <div class="breadcrumb-content">
                        <ul>
                            <li><a href="{% url 'pages:home' %}">{% trans 'Home' %}</a></li>
                            <li class="active">{% trans 'Shopping Cart' %}</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Li's Breadcrumb Area End Here -->
            <!--Shopping Cart Area Strat-->
            <div class="Shopping-cart-area pt-60 pb-60">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <form action="#">
                                <div class="table-content table-responsive">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th class="li-product-remove">{% trans 'Remove' %}</th>
                                                <th class="li-product-thumbnail">{% trans 'Images' %}</th>
                                                <th class="cart-product-name">{% trans 'Product'%}</th>
                                                <th class="li-product-quantity">{% trans 'Quantity' %}</th>
                                                <th class="li-product-subtotal">{% trans 'Price' %}</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for prod in products %}
                                            <tr>
                                                <td class="li-product-remove"><a href="{% url 'products:add_or_remove' pk=prod.id %}?next={{request.get_full_path|urlencode}}"><i class="fa fa-times"></i></a></td>
                                                <td class="li-product-thumbnail"><a href="#"><img src="{{ prod.image.url }}" alt="Li's Product Image"></a></td>
                                                <td class="li-product-name"><a href="#">{{ prod.title }}</a></td>
                                                <td class="quantity">
                                                    <label>{% trans 'Quantity' %}</label>
                                                    <div class="cart-plus-minus">
                                                        <input class="cart-plus-minus-box" value="1" type="text">
                                                    </div>
                                                </td>
                                                <td class="product-subtotal"><span class="amount">{% if prod.is_discount %}
                                                                        <span style="color:#14EF31;" class="price">${{ prod.get_price }} - </span>
                                                                        <strike style="color:red;">{{ prod.price }}</strike>
                                                                    {% else %}
                                                                        <span class="price" style="color: #B714EF">{% trans 'No discount' %} - ${{ prod.price }}</span>
                                                                    {% endif %} x {{ prod.count }}</span></td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                                 <div class="row">
                                    <div class="col-md-5 ml-auto">
                                        <div class="cart-page-total">
                                            <h2>{% trans 'Cart totals' %}</h2>
                                            <ul>
                                                <li>Total <span>${{ request|get_cart_total }}</span></li>
                                            </ul>
                                            <div class="row">
                                                <div class="col-12">
                                                    <div class="coupon-all">
                                                        <div class="minicart-button">
                                                            <a href="{% url 'orders:checkout' %}" class="li-button li-button-fullwidth li-button-dark">
                                                                <span>{% trans 'Checkout' %}</span>
                                                            </a>
                                                            <br>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!--Shopping Cart Area End-->
            <!-- Begin Footer Area -->
       {% include 'layouts/footer.html' %}

            <!-- Footer Area End Here -->
        </div>
        <!-- Body Wrapper End Here -->
        <!-- jQuery-V1.12.4 -->
       {% include 'layouts/script.html' %}
    </body>

<!-- shopping-cart31:32-->
</html>

templates/users/wishlist.html
{% load static %}
{% load i18n %}
<!doctype html>
<html class="no-js" lang="zxx">
    
<!-- wishlist31:27-->
{% include 'layouts/head.html' %}
    <body>
    <!--[if lt IE 8]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
        <!-- Begin Body Wrapper -->
        <div class="body-wrapper">
            <!-- Begin Header Area -->
            {% include 'layouts/header-base.html' %}
            <!-- Header Area End Here -->
            <!-- Begin Li's Breadcrumb Area -->
            <div class="breadcrumb-area">
                <div class="container">
                    <div class="breadcrumb-content">
                        <ul>
                            <li><a href="{% url 'pages:home' %}">{% trans 'Home' %}</a></li>
                            <li class="active">{% trans 'Wishlist' %}</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Li's Breadcrumb Area End Here -->
            <!--Wishlist Area Strat-->
            <div class="wishlist-area pt-60 pb-60">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <form action="#">
                                <div class="table-content table-responsive">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th class="li-product-remove">{% trans 'remove' %}</th>
                                                <th class="li-product-thumbnail">{% trans 'Images' %}</th>
                                                <th class="cart-product-name">{% trans 'Product' %}</th>
                                                <th class="li-product-price">{% trans 'Price' %}</th>
                                                <th class="li-product-stock-status">{% trans 'Stock Status' %}</th>
                                                <th class="li-product-add-cart">{% trans 'Add to cart' %}</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for prod in products %}
                                            <tr>
                                                <td class="li-product-remove"><a href="{% url 'products:add_or_remov' pk=prod.id %}?next={{request.get_full_path|urlencode}}"><i class="fa fa-times"></i></a></td>
                                                <td class="li-product-thumbnail"><a href="{% url 'products:list' %}"><img src="{{ prod.image.url }}" alt=""></a></td>
                                                <td class="li-product-name"><a href="{% url 'products:list' %}">{{ prod.title }}</a></td>
                                                <td class="li-product-price"><span class="amount">{% if prod.is_discount %}
                                                                        <span style="color:#14EF31;" class="price">${{ prod.get_price }} - </span>
                                                                        <strike style="color:red;">{{ prod.price }}</strike>
                                                                    {% else %}
                                                                        <span class="price" style="color: #B714EF">{% trans 'No discount' %} - ${{ prod.price }}</span>
                                                                    {% endif %} x {{ prod.count }}</span></td>
                                                {% if prod.is_available %}
                                                    <td class="li-product-stock-status"><span class="in-stock" style="color:#0DFF02;">{% trans 'In stock' %}</span></td>
                                                {% else %}
                                                    <td class="li-product-stock-status"><span class="in-stock" style="color:red;">{% trans 'Not in stock' %}</span></td>
                                                {% endif %}
                                                <td class="li-product-add-cart"><a href="{% url 'products:add_or_remove' pk=prod.id %}?next={{request.get_full_path|urlencode}}">{% trans 'add to cart' %}</a></td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!--Wishlist Area End-->
            <!-- Begin Footer Area -->
            {% include 'layouts/footer.html' %}

            <!-- Footer Area End Here -->
            <!-- Begin Modal Area -->
            <!-- Modal Area End Here -->
        </div>
        <!-- Body Wrapper End Here -->
        <!-- jQuery-V1.12.4 -->
        {% include 'layouts/script.html' %}
    </body>

<!-- wishlist31:30-->
</html>